CREATE TABLE
    `osu-demo-project-2026-508513.crypto_dataset.crypto_history_combined` AS

SELECT
    btc.TIMESTAMP,

    -- Bitcoin columns
    btc.UNIT AS BTC_UNIT,
    btc.TYPE AS BTC_TYPE,
    btc.MARKET AS BTC_MARKET,
    btc.INSTRUMENT AS BTC_INSTRUMENT,
    btc.OPEN AS BTC_OPEN,
    btc.HIGH AS BTC_HIGH,
    btc.LOW AS BTC_LOW,
    btc.CLOSE AS BTC_CLOSE,
    btc.FIRST_MESSAGE_TIMESTAMP AS BTC_FIRST_MESSAGE_TIMESTAMP,
    btc.LAST_MESSAGE_TIMESTAMP AS BTC_LAST_MESSAGE_TIMESTAMP,
    btc.FIRST_MESSAGE_VALUE AS BTC_FIRST_MESSAGE_VALUE,
    btc.HIGH_MESSAGE_VALUE AS BTC_HIGH_MESSAGE_VALUE,
    btc.HIGH_MESSAGE_TIMESTAMP AS BTC_HIGH_MESSAGE_TIMESTAMP,
    btc.LOW_MESSAGE_VALUE AS BTC_LOW_MESSAGE_VALUE,
    btc.LOW_MESSAGE_TIMESTAMP AS BTC_LOW_MESSAGE_TIMESTAMP,
    btc.LAST_MESSAGE_VALUE AS BTC_LAST_MESSAGE_VALUE,
    btc.TOTAL_INDEX_UPDATES AS BTC_TOTAL_INDEX_UPDATES,
    btc.VOLUME AS BTC_VOLUME,
    btc.QUOTE_VOLUME AS BTC_QUOTE_VOLUME,
    btc.VOLUME_TOP_TIER AS BTC_VOLUME_TOP_TIER,
    btc.QUOTE_VOLUME_TOP_TIER AS BTC_QUOTE_VOLUME_TOP_TIER,
    btc.VOLUME_DIRECT AS BTC_VOLUME_DIRECT,
    btc.QUOTE_VOLUME_DIRECT AS BTC_QUOTE_VOLUME_DIRECT,
    btc.VOLUME_TOP_TIER_DIRECT AS BTC_VOLUME_TOP_TIER_DIRECT,
    btc.QUOTE_VOLUME_TOP_TIER_DIRECT AS BTC_QUOTE_VOLUME_TOP_TIER_DIRECT,

    -- Bitcoin calculated range
    btc.HIGH - btc.LOW AS BTC_RANGE,

    -- Ethereum columns
    eth.UNIT AS ETH_UNIT,
    eth.TYPE AS ETH_TYPE,
    eth.MARKET AS ETH_MARKET,
    eth.INSTRUMENT AS ETH_INSTRUMENT,
    eth.OPEN AS ETH_OPEN,
    eth.HIGH AS ETH_HIGH,
    eth.LOW AS ETH_LOW,
    eth.CLOSE AS ETH_CLOSE,
    eth.FIRST_MESSAGE_TIMESTAMP AS ETH_FIRST_MESSAGE_TIMESTAMP,
    eth.LAST_MESSAGE_TIMESTAMP AS ETH_LAST_MESSAGE_TIMESTAMP,
    eth.FIRST_MESSAGE_VALUE AS ETH_FIRST_MESSAGE_VALUE,
    eth.HIGH_MESSAGE_VALUE AS ETH_HIGH_MESSAGE_VALUE,
    eth.HIGH_MESSAGE_TIMESTAMP AS ETH_HIGH_MESSAGE_TIMESTAMP,
    eth.LOW_MESSAGE_VALUE AS ETH_LOW_MESSAGE_VALUE,
    eth.LOW_MESSAGE_TIMESTAMP AS ETH_LOW_MESSAGE_TIMESTAMP,
    eth.LAST_MESSAGE_VALUE AS ETH_LAST_MESSAGE_VALUE,
    eth.TOTAL_INDEX_UPDATES AS ETH_TOTAL_INDEX_UPDATES,
    eth.VOLUME AS ETH_VOLUME,
    eth.QUOTE_VOLUME AS ETH_QUOTE_VOLUME,
    eth.VOLUME_TOP_TIER AS ETH_VOLUME_TOP_TIER,
    eth.QUOTE_VOLUME_TOP_TIER AS ETH_QUOTE_VOLUME_TOP_TIER,
    eth.VOLUME_DIRECT AS ETH_VOLUME_DIRECT,
    eth.QUOTE_VOLUME_DIRECT AS ETH_QUOTE_VOLUME_DIRECT,
    eth.VOLUME_TOP_TIER_DIRECT AS ETH_VOLUME_TOP_TIER_DIRECT,
    eth.QUOTE_VOLUME_TOP_TIER_DIRECT AS ETH_QUOTE_VOLUME_TOP_TIER_DIRECT,

    -- Ethereum calculated range
    eth.HIGH - eth.LOW AS ETH_RANGE

FROM
    `osu-demo-project-2026-508513.crypto_dataset.crypto_history_BTC` AS btc

LEFT JOIN
    `osu-demo-project-2026-508513.crypto_dataset.crypto_history_ETH` AS eth
ON
    btc.TIMESTAMP = eth.TIMESTAMP

ORDER BY
    btc.TIMESTAMP;